# Project automatically converted from an existing Wisteria 1.x.x project
# For more configuration options, see the Wisteria wiki
[project]
name = "Anenome"

[task]

[task_main]
output = ["target/{TASK_NAME}/{PROJECT_NAME}.jar"]
source = ["src/"]
